"""Add selected offer

Revision ID: 47a72b3ea7b0
Revises: 8bba2fa898d3
Create Date: 2026-05-01 16:05:42.792391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a72b3ea7b0'
down_revision = '8bba2fa898d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_offer_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_request_selected_offer_id_offer'), 'offer', ['selected_offer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_request_selected_offer_id_offer'), type_='foreignkey')
        batch_op.drop_column('selected_offer_id')

    # ### end Alembic commands ###
