"""Add column for skill to learn

Revision ID: 8bba2fa898d3
Revises: b04620540c36
Create Date: 2026-04-28 12:30:29.327114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bba2fa898d3'
down_revision = 'b04620540c36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('skill_to_learn', sa.String(length=255), nullable=False))
        batch_op.alter_column('owner_skill_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.alter_column('owner_skill_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('skill_to_learn')

    # ### end Alembic commands ###
