"""Add ON DELETE RESTRICT

Revision ID: de8768bdeab7
Revises: 47a72b3ea7b0
Create Date: 2026-05-13 20:26:00.188827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de8768bdeab7'
down_revision = '47a72b3ea7b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_offer_offer_skill_id_skill'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_offer_request_id_request'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_offer_request_id_request'), 'request', ['request_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_offer_offer_skill_id_skill'), 'skill', ['offer_skill_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_request_owner_skill_id_skill'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_request_owner_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_request_owner_skill_id_skill'), 'skill', ['owner_skill_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_request_owner_id_user'), 'user', ['owner_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_skill_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_skill_user_id_user'), 'user', ['user_id'], ['id'], ondelete='RESTRICT')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_skill_user_id_user'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_skill_user_id_user'), 'user', ['user_id'], ['id'])

    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_request_owner_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_request_owner_skill_id_skill'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_request_owner_id_user'), 'user', ['owner_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_request_owner_skill_id_skill'), 'skill', ['owner_skill_id'], ['id'])

    with op.batch_alter_table('offer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_offer_offer_skill_id_skill'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_offer_request_id_request'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_offer_request_id_request'), 'request', ['request_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_offer_offer_skill_id_skill'), 'skill', ['offer_skill_id'], ['id'])

    # ### end Alembic commands ###
